# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PrefixProxy
                                 A QGIS plugin
 Adds prefix proxy addresses to connections
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-08-02
        copyright            : (C) 2023 by Dror Bogin
        email                : dror.bogin@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PrefixProxy class from file PrefixProxy.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .prefix_proxy import PrefixProxy
    return PrefixProxy(iface)
